line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "W", "I", "B", "UP", "N", "S", "C4", "SIM", "RUF"]
ignore = ["E203", "E501"]

[lint.per-file-ignores]
"tests/**/*.py" = ["S101", "S105", "S106", "S311", "N802", "N803", "SIM117"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
